FROM node:18.6.0

WORKDIR /skytransfer

ENV SELF_HOSTED=true

# Install pnpm
RUN npm install -g pnpm

# Copy everything over
COPY ./server .

# Install all production dependencies
RUN pnpm i -P --frozen-lockfile

# Build the application
RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start"]